/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package y_student;
import authenticate.logIn;
import config.config;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import net.proteanit.sql.DbUtils;
import x_admin.adminDashboard;
import x_admin.sysLogs;
/**
 *
 * @author juls
 */
public class studDashboard extends javax.swing.JFrame {
        private String currentImagePath;
        private String currentUserName;
        
        
      public studDashboard(String name, String imagePath) {
        if (config.stopIllegalAccess(this)) return;
        initComponents(); 
        displayDetails();
        this.currentUserName = name;
        this.currentImagePath = imagePath;
        namee.setText(currentUserName);
        nameee.setText("Welcome, " + config.getName());
        setupDashboard();
       
    }
    public studDashboard() {
        if (config.stopIllegalAccess(this)) return;
        initComponents();
        namee.setText(config.getName()); 
        displayProfileImage();

        this.currentUserName = config.getName();
        this.currentImagePath = config.getImage();
        config conf = new config();
        String[] settings = conf.getSystemSettings();
        sem.setText(settings[0]); 
        year.setText(settings[1]);
        namee.setText(currentUserName);
        setupDashboard();
        
        displayStatistics();
        conf.designTable(tbl_recent); 
        displayRecentActivity();
        
        //ottttttttttttttttttttttesnsnssnns
    }
    
    public void displayStatistics() {
    try (Connection conn = DriverManager.getConnection("jdbc:sqlite:aes.db")) {
        
        // 1. IHAPON PILA NA KA MAESTRO ANG NA-EVALUATE NA SA STUDENT
        String sqlEvaluated = "SELECT COUNT(*) FROM tbl_evaluation WHERE s_u_id = ?";
        PreparedStatement pst1 = conn.prepareStatement(sqlEvaluated);
        pst1.setString(1, config.getID()); // Session ID sa Student
        ResultSet rs1 = pst1.executeQuery();
        if (rs1.next()) {
            totEvaluated.setText("" + rs1.getInt(1));
        }

        String sqlTotalTeachers = "SELECT COUNT(*) FROM tbl_user WHERE u_type = 'Teacher' AND u_status = 'Approved'";
        ResultSet rs2 = conn.createStatement().executeQuery(sqlTotalTeachers);
        if (rs2.next()) {
            int totalTeachers = rs2.getInt(1);
            int evaluated = Integer.parseInt(totEvaluated.getText());
            int pending = totalTeachers - evaluated;
            
            // Siguruha nga dili negative (kung naay error sa data)
            pendingss.setText("" + (pending < 0 ? 0 : pending));
        }

    } catch (SQLException e) {
        System.out.println("Stats Error: " + e.getMessage());
    }
}
    public void setupDashboard() {
    config conf = new config();
    
    // 1. Get the current size of your profile label
    int w = profile.getWidth();
    int h = profile.getHeight();
    
    // 2. Fallback in case the UI hasn't calculated the size yet
    if(w <= 0) w = 120; 
    if(h <= 0) h = 120;

    // 3. Call the logic (Make sure you already updated config.java as we discussed!)
    if (currentImagePath != null && !currentImagePath.isEmpty()) {
        profile.setIcon(conf.resizeImage(currentImagePath, null, w, h));
    }
    

        conf.manageHover(a); conf.manageHover(i); conf.manageHover(d);
        conf.manageHover(e); conf.manageHover(g); 
       
    
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void displayProfileImage() {
        String path = config.getImage();
        if (path != null && !path.isEmpty()) {
            config conf = new config();
            profile.setIcon(conf.resizeImage(path, null, profile.getWidth(), profile.getHeight()));
        }
    }

    @SuppressWarnings("unchecked")
    public void displayRecentActivity() {
    String sql = "SELECT u.u_name AS 'EVALUATED', e.e_average AS 'AVERAGE', e.e_date AS 'SUBMITTED' "
               + "FROM tbl_evaluation e "
               + "JOIN tbl_user u ON e.t_u_id = u.u_id "
               + "WHERE e.s_u_id = ? "
               + "ORDER BY e.e_id DESC LIMIT 5";
    
    try (Connection conn = DriverManager.getConnection("jdbc:sqlite:aes.db");
         PreparedStatement pst = conn.prepareStatement(sql)) {
        
        pst.setString(1, config.getID()); // Session ID sa Student
        ResultSet rs = pst.executeQuery();
        
        // I-display sa imong JTable
        tbl_recent.setModel(DbUtils.resultSetToTableModel(rs));
        
    } catch (SQLException e) {
        System.out.println("Recent Activity Error: " + e.getMessage());
    }
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        a = new javax.swing.JPanel();
        account = new javax.swing.JLabel();
        d = new javax.swing.JPanel();
        dashbord = new javax.swing.JLabel();
        e = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        g = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        h = new javax.swing.JPanel();
        account1 = new javax.swing.JLabel();
        i = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        user1 = new javax.swing.JLabel();
        profile = new config.CircularLabel();
        namee = new javax.swing.JLabel();
        totp4 = new javax.swing.JLabel();
        nameee = new javax.swing.JLabel();
        A = new javax.swing.JPanel();
        activeE = new javax.swing.JLabel();
        pendingss = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        activeE2 = new javax.swing.JLabel();
        activeE3 = new javax.swing.JLabel();
        totp1 = new javax.swing.JLabel();
        C = new javax.swing.JPanel();
        totEvaluated = new javax.swing.JLabel();
        users5 = new javax.swing.JLabel();
        totp = new javax.swing.JLabel();
        D = new javax.swing.JPanel();
        eprog2 = new javax.swing.JLabel();
        sem = new javax.swing.JLabel();
        totp2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        nameee1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_recent = new javax.swing.JTable();
        D1 = new javax.swing.JPanel();
        eprog3 = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        totp3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 33, 71));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(45, 52, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setBackground(new java.awt.Color(197, 179, 88));
        a.setForeground(new java.awt.Color(197, 179, 88));
        a.setPreferredSize(new java.awt.Dimension(142, 30));

        account.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        account.setText("MY PROFILE");
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout aLayout = new javax.swing.GroupLayout(a);
        a.setLayout(aLayout);
        aLayout.setHorizontalGroup(
            aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(account, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        aLayout.setVerticalGroup(
            aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(account, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 160, -1));

        d.setBackground(new java.awt.Color(197, 179, 88));
        d.setForeground(new java.awt.Color(197, 179, 88));
        d.setPreferredSize(new java.awt.Dimension(142, 30));
        d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dMouseEntered(evt);
            }
        });
        d.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashbord.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        dashbord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashbord.setText("DASHBOARD");
        dashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashbordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashbordMouseEntered(evt);
            }
        });
        d.add(dashbord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, -1));

        e.setBackground(new java.awt.Color(197, 179, 88));
        e.setForeground(new java.awt.Color(197, 179, 88));
        e.setPreferredSize(new java.awt.Dimension(142, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("VIEW EVALUATIONS");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout eLayout = new javax.swing.GroupLayout(e);
        e.setLayout(eLayout);
        eLayout.setHorizontalGroup(
            eLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        eLayout.setVerticalGroup(
            eLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, -1));

        g.setBackground(new java.awt.Color(197, 179, 88));
        g.setForeground(new java.awt.Color(197, 179, 88));

        user.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setText("EVALUATE");
        user.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout gLayout = new javax.swing.GroupLayout(g);
        g.setLayout(gLayout);
        gLayout.setHorizontalGroup(
            gLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gLayout.setVerticalGroup(
            gLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, 30));

        h.setBackground(new java.awt.Color(197, 179, 88));
        h.setForeground(new java.awt.Color(197, 179, 88));
        h.setPreferredSize(new java.awt.Dimension(142, 30));

        account1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        account1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        account1.setText("SYSTEM LOGS");
        account1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                account1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hLayout = new javax.swing.GroupLayout(h);
        h.setLayout(hLayout);
        hLayout.setHorizontalGroup(
            hLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(account1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        hLayout.setVerticalGroup(
            hLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(account1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 160, -1));

        i.setBackground(new java.awt.Color(44, 62, 80));
        i.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 179, 88)));

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow20.png"))); // NOI18N

        Back.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        Back.setForeground(new java.awt.Color(197, 179, 88));
        Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back.setText("Log out");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout iLayout = new javax.swing.GroupLayout(i);
        i.setLayout(iLayout);
        iLayout.setHorizontalGroup(
            iLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iLayout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
        );
        iLayout.setVerticalGroup(
            iLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel2.add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 110, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 430));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setForeground(new java.awt.Color(240, 240, 240));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        user1.setForeground(new java.awt.Color(197, 179, 88));
        user1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user1.setText("STUDENT DASHBOARD");
        user1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user1MouseClicked(evt);
            }
        });
        jPanel3.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 680, 70));

        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        jPanel3.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        namee.setBackground(new java.awt.Color(44, 62, 80));
        namee.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        namee.setForeground(new java.awt.Color(240, 240, 240));
        jPanel3.add(namee, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 140, 30));

        totp4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/student.png"))); // NOI18N
        jPanel3.add(totp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 60, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        nameee.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        nameee.setForeground(new java.awt.Color(197, 179, 88));
        nameee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameee.setText("Welcome back!");
        nameee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameeeMouseClicked(evt);
            }
        });
        jPanel1.add(nameee, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 330, 60));

        A.setBackground(new java.awt.Color(45, 52, 54));
        A.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        activeE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        activeE.setForeground(new java.awt.Color(240, 240, 240));
        activeE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activeE.setText("Teachers to Evaluate");
        A.add(activeE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 20));

        pendingss.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        pendingss.setForeground(new java.awt.Color(240, 240, 240));
        pendingss.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A.add(pendingss, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, 40));

        jPanel7.setBackground(new java.awt.Color(45, 52, 54));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        activeE2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        activeE2.setForeground(new java.awt.Color(240, 240, 240));
        activeE2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activeE2.setText("Evaluations");
        jPanel7.add(activeE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        activeE3.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        activeE3.setForeground(new java.awt.Color(240, 240, 240));
        activeE3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(activeE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 120, 40));

        A.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 240, 110));

        totp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ttto.png"))); // NOI18N
        A.add(totp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        jPanel1.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 240, 70));

        C.setBackground(new java.awt.Color(45, 52, 54));
        C.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totEvaluated.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        totEvaluated.setForeground(new java.awt.Color(240, 240, 240));
        totEvaluated.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C.add(totEvaluated, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, 40));

        users5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        users5.setForeground(new java.awt.Color(240, 240, 240));
        users5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        users5.setText("Total Evaluated");
        C.add(users5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        totp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/totpp.png"))); // NOI18N
        C.add(totp, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 120, 30));

        jPanel1.add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 240, 70));

        D.setBackground(new java.awt.Color(45, 52, 54));
        D.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eprog2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eprog2.setForeground(new java.awt.Color(240, 240, 240));
        eprog2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eprog2.setText("Current Semester");
        D.add(eprog2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 20));

        sem.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        sem.setForeground(new java.awt.Color(240, 240, 240));
        sem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D.add(sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, 40));

        totp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/calendar.png"))); // NOI18N
        D.add(totp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 30));

        jPanel1.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 240, 70));

        jPanel4.setBackground(new java.awt.Color(45, 52, 54));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameee1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        nameee1.setForeground(new java.awt.Color(197, 179, 88));
        nameee1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameee1.setText("Your Recent Evaluations:");
        nameee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameee1MouseClicked(evt);
            }
        });
        jPanel4.add(nameee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 330, 60));

        tbl_recent.setBackground(new java.awt.Color(45, 52, 54));
        tbl_recent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_recent.setForeground(new java.awt.Color(240, 240, 240));
        tbl_recent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_recent.setFocusable(false);
        tbl_recent.setGridColor(new java.awt.Color(45, 52, 54));
        tbl_recent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_recentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_recent);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 330, 350));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 350, 430));

        D1.setBackground(new java.awt.Color(45, 52, 54));
        D1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eprog3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eprog3.setForeground(new java.awt.Color(240, 240, 240));
        eprog3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eprog3.setText("Current Year");
        D1.add(eprog3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, -1));

        year.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        year.setForeground(new java.awt.Color(240, 240, 240));
        year.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, 40));

        totp3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/year.png"))); // NOI18N
        D1.add(totp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 80, 30));

        jPanel1.add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 240, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void displayDetails(){
        namee.setText(config.getName()); 

        String path = config.getImage(); 
        if (path != null) {
            config conf = new config();
            profile.setIcon(conf.resizeImage(path, null, 120, 120));}
    }
    
    public void syncUserSession() {
    // This works for EVERYONE
    namee.setText(config.getName());
    
    String path = config.getImage();
    if (path != null && !path.isEmpty()) {
        config conf = new config();
        // Uses the proportional resizing (anti-squeeze) we made
        profile.setIcon(conf.resizeImage(path, null, profile.getWidth(), profile.getHeight()));
    }
}
    
    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        seditUser accFrame = new seditUser();
        accFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountMouseClicked

    private void dashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashbordMouseClicked
        studDashboard dashFrame = new studDashboard();
        dashFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashbordMouseClicked

    private void dashbordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashbordMouseEntered

    }//GEN-LAST:event_dashbordMouseEntered

    private void dMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseEntered

    }//GEN-LAST:event_dMouseEntered

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        viewEvals viewFrame = new viewEvals();
        viewFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        studEvaluate eFrame = new studEvaluate();
        eFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userMouseClicked

    private void userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_userMouseEntered

    private void account1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_account1MouseClicked
        logsStudent lS = new logsStudent();
        lS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_account1MouseClicked

    private void user1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_user1MouseClicked

    private void nameeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameeeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nameeeMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        seditUser editFrame = new seditUser();
        editFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked

        config conf = new config();
        int confirm = javax.swing.JOptionPane.showConfirmDialog(null,
            "Do you really want to log out?",
            "Logout Confirmation",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            conf.logEvent("User Logged Out");
            new logIn().setVisible(true);
            this.dispose();
        } else {
            System.out.println("Logout cancelled by user.");
        }
    }//GEN-LAST:event_BackMouseClicked

    private void tbl_recentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_recentMouseClicked

    }//GEN-LAST:event_tbl_recentMouseClicked

    private void nameee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameee1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nameee1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A;
    private javax.swing.JLabel Back;
    private javax.swing.JPanel C;
    private javax.swing.JPanel D;
    private javax.swing.JPanel D1;
    private javax.swing.JPanel a;
    private javax.swing.JLabel account;
    private javax.swing.JLabel account1;
    private javax.swing.JLabel activeE;
    private javax.swing.JLabel activeE2;
    private javax.swing.JLabel activeE3;
    private javax.swing.JLabel back;
    private javax.swing.JPanel d;
    private javax.swing.JLabel dashbord;
    private javax.swing.JPanel e;
    private javax.swing.JLabel eprog2;
    private javax.swing.JLabel eprog3;
    private javax.swing.JPanel g;
    private javax.swing.JPanel h;
    private javax.swing.JPanel i;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel namee;
    private javax.swing.JLabel nameee;
    private javax.swing.JLabel nameee1;
    private javax.swing.JLabel pendingss;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel sem;
    private javax.swing.JTable tbl_recent;
    private javax.swing.JLabel totEvaluated;
    private javax.swing.JLabel totp;
    private javax.swing.JLabel totp1;
    private javax.swing.JLabel totp2;
    private javax.swing.JLabel totp3;
    private javax.swing.JLabel totp4;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel users5;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
