package authenticate;

 
import main.Javagui;
import config.config;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;

public class signup1 extends javax.swing.JFrame {

    public signup1() {
        initComponents();
        config conf = new config();
        conf.manageHover(back);
        conf.manageHover(r);
        conf.manageHover(bg);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        signupPanel = new javax.swing.JPanel();
        back = new javax.swing.JPanel();
        backlabel = new javax.swing.JLabel();
        r = new javax.swing.JPanel();
        registerbuton1 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        gg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();
        passs = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        emails = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaption);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 33, 71));
        jPanel3.setAutoscrolls(true);
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 400));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(45, 52, 54));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signupPanel.setBackground(new java.awt.Color(0, 204, 51));
        signupPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signupPanel.setForeground(new java.awt.Color(0, 204, 51));
        signupPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signupPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(signupPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        back.setBackground(new java.awt.Color(197, 179, 88));
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setForeground(new java.awt.Color(0, 204, 51));

        backlabel.setBackground(new java.awt.Color(0, 153, 51));
        backlabel.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        backlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backlabel.setText("Back");
        backlabel.setFocusable(false);
        backlabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel4.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, 30));

        r.setBackground(new java.awt.Color(0, 204, 51));
        r.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r.setForeground(new java.awt.Color(0, 204, 51));
        r.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        r.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerbuton1.setBackground(new java.awt.Color(0, 153, 51));
        registerbuton1.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        registerbuton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerbuton1.setText("Register");
        registerbuton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registerbuton1.setFocusable(false);
        registerbuton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerbuton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbuton1MouseClicked(evt);
            }
        });
        r.add(registerbuton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel4.add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 80, -1));

        bg.setBackground(new java.awt.Color(0, 33, 71));
        bg.setForeground(new java.awt.Color(0, 33, 71));

        gg.setBackground(new java.awt.Color(197, 179, 88));
        gg.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        gg.setForeground(new java.awt.Color(197, 179, 88));
        gg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gg.setText("I already have an account");
        gg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gg.setFocusable(false);
        gg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ggMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(gg, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gg, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel4.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 240, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Email:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, 30));

        textLabel.setBackground(new java.awt.Color(0, 33, 71));
        textLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        textLabel.setForeground(new java.awt.Color(240, 240, 240));
        textLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLabel.setText("Sign Up");
        jPanel4.add(textLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 450, 35));

        passs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        passs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passsActionPerformed(evt);
            }
        });
        jPanel4.add(passs, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 190, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Password:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, 30));

        emails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        emails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailsActionPerformed(evt);
            }
        });
        jPanel4.add(emails, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 190, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Name:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 30));

        name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel4.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 190, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 500));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Academic Evaluations no.2.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 450, 190));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(197, 179, 88));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WELCOME TO ACADEMIC EVALUATIONS!");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 450, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void ggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ggMouseClicked
        logIn loginFrame = new logIn();
        loginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ggMouseClicked

    private void backlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlabelMouseClicked
        Javagui javaguiFrame = new Javagui();
        javaguiFrame.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backlabelMouseClicked

    private void passsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passsActionPerformed

    private void emailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailsActionPerformed

    private void registerbuton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbuton1MouseClicked
        config con = new config();
        String uName = name.getText();
        String uEmail = emails.getText();
        String uPass = new String(passs.getPassword());

        // Step 1: Insert into the main User Table
        String sqlUser = "INSERT INTO tbl_user (u_name, u_email, u_pass, u_type, u_status) VALUES (?, ?, ?, ?, ?)";

        if(con.addRecord(sqlUser, uName, uEmail, uPass, "Student", "Pending") == 1) {

            // Step 2: Insert into the specialized table based on the type
            
                String sqlTeacher = "INSERT INTO tbl_teacher ( t_name, t_email, t_pass, t_status) VALUES (?,?,?, ?)";
                con.addRecord(sqlTeacher, uName, uEmail, uPass, "Pending");
            } 
            
            name.setText("");
            emails.setText("");
            passs.setText("");
            /*else if(type.equals("Student")) {
                String sqlStudent = "INSERT INTO tbl_student (s_name, s_email) VALUES (?, ?)";
                con.addRecord(sqlStudent, uName, uEmail);
            }*/
            JOptionPane.showMessageDialog(null, "Thank for registering, please wait for admins approval. Tanks!");
            new logIn().setVisible(true);
            this.dispose();

        
    }//GEN-LAST:event_registerbuton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel back;
    public javax.swing.JLabel backlabel;
    public javax.swing.JPanel bg;
    public javax.swing.JTextField emails;
    public javax.swing.JLabel gg;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JTextField name;
    public javax.swing.JPasswordField passs;
    public javax.swing.JPanel r;
    public javax.swing.JLabel registerbuton1;
    public javax.swing.JPanel signupPanel;
    public javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
