/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package x_admin;

import authenticate.logIn;
import config.config;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import y_student.sUserAccount;
/**
 *
 * @author juls
 */
public class addUser extends javax.swing.JFrame {
    String destination = "";
    /**
     * Creates new form addUser
     */
    public addUser() {
        //if (config.stopIllegalAccess(this)) return;
        initComponents();
        nameee.setText(config.getName()); 
        displayProfileImage();
        config conf = new config();
         conf.manageHover(SAVE);
        conf.manageHover(CANCEL);
        conf.manageHover(change);
        conf.manageHover(bg);
        conf.manageHover(a);
        conf.manageHover(b);
        conf.manageHover(e);
        conf.manageHover(d);
        conf.manageHover(g);
        conf.manageHover(h);
        conf.manageHover(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void displayProfileImage() {
        String path = config.getImage();
        if (path != null && !path.isEmpty()) {
            config conf = new config();
            profile.setIcon(conf.resizeImage(path, null, profile.getWidth(), profile.getHeight()));
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        user1 = new javax.swing.JLabel();
        namee = new javax.swing.JLabel();
        profile = new config.CircularLabel();
        totp4 = new javax.swing.JLabel();
        ID = new javax.swing.JPanel();
        id = new java.awt.Label();
        NAME = new javax.swing.JPanel();
        name = new java.awt.Label();
        nameee = new java.awt.TextField();
        EMAIL = new javax.swing.JPanel();
        email = new java.awt.Label();
        emaill = new java.awt.TextField();
        PASS = new javax.swing.JPanel();
        pass = new java.awt.Label();
        passs = new java.awt.TextField();
        USERTYPE = new javax.swing.JPanel();
        usertype = new java.awt.Label();
        type = new javax.swing.JComboBox<>();
        SAVE = new javax.swing.JPanel();
        save = new javax.swing.JLabel();
        idd = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        change = new javax.swing.JPanel();
        changepic = new javax.swing.JLabel();
        CANCEL = new javax.swing.JPanel();
        cancel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        a = new javax.swing.JPanel();
        account = new javax.swing.JLabel();
        b = new javax.swing.JPanel();
        evaluations = new javax.swing.JLabel();
        d = new javax.swing.JPanel();
        dashbord = new javax.swing.JLabel();
        e = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        g = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        h = new javax.swing.JPanel();
        account1 = new javax.swing.JLabel();
        i = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 33, 71));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(44, 62, 80));
        bg.setForeground(new java.awt.Color(240, 240, 240));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        user1.setForeground(new java.awt.Color(240, 240, 240));
        user1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user1.setText("ADD USER");
        user1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user1MouseClicked(evt);
            }
        });
        bg.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 680, 70));

        namee.setBackground(new java.awt.Color(44, 62, 80));
        namee.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        namee.setForeground(new java.awt.Color(240, 240, 240));
        bg.add(namee, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 140, 30));

        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        bg.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        totp4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/admin.png"))); // NOI18N
        bg.add(totp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 70, 50));

        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        id.setAlignment(java.awt.Label.CENTER);
        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id.setName(""); // NOI18N
        id.setText("ID:");

        javax.swing.GroupLayout IDLayout = new javax.swing.GroupLayout(ID);
        ID.setLayout(IDLayout);
        IDLayout.setHorizontalGroup(
            IDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        IDLayout.setVerticalGroup(
            IDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 80, 30));

        name.setAlignment(java.awt.Label.CENTER);
        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setName(""); // NOI18N
        name.setText("Name:");

        javax.swing.GroupLayout NAMELayout = new javax.swing.GroupLayout(NAME);
        NAME.setLayout(NAMELayout);
        NAMELayout.setHorizontalGroup(
            NAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        NAMELayout.setVerticalGroup(
            NAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 80, 30));

        nameee.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameeeActionPerformed(evt);
            }
        });
        jPanel1.add(nameee, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 270, 30));

        email.setAlignment(java.awt.Label.CENTER);
        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setName(""); // NOI18N
        email.setText("Email:");

        javax.swing.GroupLayout EMAILLayout = new javax.swing.GroupLayout(EMAIL);
        EMAIL.setLayout(EMAILLayout);
        EMAILLayout.setHorizontalGroup(
            EMAILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        EMAILLayout.setVerticalGroup(
            EMAILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 80, 30));

        emaill.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emaill.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emaill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emaillActionPerformed(evt);
            }
        });
        jPanel1.add(emaill, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 270, 30));

        pass.setAlignment(java.awt.Label.CENTER);
        pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass.setName(""); // NOI18N
        pass.setText("Password:");

        javax.swing.GroupLayout PASSLayout = new javax.swing.GroupLayout(PASS);
        PASS.setLayout(PASSLayout);
        PASSLayout.setHorizontalGroup(
            PASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PASSLayout.setVerticalGroup(
            PASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(PASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 80, 30));

        passs.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passs.setEnabled(false);
        passs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passs.setForeground(new java.awt.Color(240, 240, 240));
        passs.setText("Default: P@ssw0rd");
        passs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passsActionPerformed(evt);
            }
        });
        jPanel1.add(passs, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 270, 30));

        usertype.setAlignment(java.awt.Label.CENTER);
        usertype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usertype.setName(""); // NOI18N
        usertype.setText("Usertype:");

        javax.swing.GroupLayout USERTYPELayout = new javax.swing.GroupLayout(USERTYPE);
        USERTYPE.setLayout(USERTYPELayout);
        USERTYPELayout.setHorizontalGroup(
            USERTYPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usertype, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        USERTYPELayout.setVerticalGroup(
            USERTYPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usertype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(USERTYPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 80, 30));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Student", "Teacher" }));
        type.setName(""); // NOI18N
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 270, 30));

        SAVE.setBackground(new java.awt.Color(39, 174, 96));
        SAVE.setForeground(new java.awt.Color(240, 240, 240));

        save.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save.setText("SAVE");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SAVELayout = new javax.swing.GroupLayout(SAVE);
        SAVE.setLayout(SAVELayout);
        SAVELayout.setHorizontalGroup(
            SAVELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        SAVELayout.setVerticalGroup(
            SAVELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 60, 30));

        javax.swing.GroupLayout iddLayout = new javax.swing.GroupLayout(idd);
        idd.setLayout(iddLayout);
        iddLayout.setHorizontalGroup(
            iddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        iddLayout.setVerticalGroup(
            iddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(idd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 270, 30));

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 4));
        image.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        image.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        change.setBackground(new java.awt.Color(197, 179, 88));
        change.setForeground(new java.awt.Color(240, 240, 240));

        changepic.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        changepic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changepic.setText("ADD IMAGE");
        changepic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changepicMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout changeLayout = new javax.swing.GroupLayout(change);
        change.setLayout(changeLayout);
        changeLayout.setHorizontalGroup(
            changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changepic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        changeLayout.setVerticalGroup(
            changeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changepic, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 130, 30));

        CANCEL.setBackground(new java.awt.Color(192, 57, 43));
        CANCEL.setForeground(new java.awt.Color(240, 240, 240));

        cancel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("CANCEL");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CANCELLayout = new javax.swing.GroupLayout(CANCEL);
        CANCEL.setLayout(CANCELLayout);
        CANCELLayout.setHorizontalGroup(
            CANCELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        CANCELLayout.setVerticalGroup(
            CANCELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(CANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 60, 30));

        jPanel2.setBackground(new java.awt.Color(45, 52, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setBackground(new java.awt.Color(197, 179, 88));
        a.setForeground(new java.awt.Color(197, 179, 88));
        a.setPreferredSize(new java.awt.Dimension(142, 30));

        account.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        account.setText("MY PROFILE");
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout aLayout = new javax.swing.GroupLayout(a);
        a.setLayout(aLayout);
        aLayout.setHorizontalGroup(
            aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(account, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        aLayout.setVerticalGroup(
            aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(account, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 160, -1));

        b.setBackground(new java.awt.Color(197, 179, 88));
        b.setForeground(new java.awt.Color(197, 179, 88));
        b.setPreferredSize(new java.awt.Dimension(142, 30));

        evaluations.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        evaluations.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        evaluations.setText("VIEW EVALUATIONS");
        evaluations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evaluationsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bLayout = new javax.swing.GroupLayout(b);
        b.setLayout(bLayout);
        bLayout.setHorizontalGroup(
            bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(evaluations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bLayout.setVerticalGroup(
            bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(evaluations, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, -1));

        d.setBackground(new java.awt.Color(197, 179, 88));
        d.setForeground(new java.awt.Color(197, 179, 88));
        d.setPreferredSize(new java.awt.Dimension(142, 30));

        dashbord.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        dashbord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashbord.setText("DASHBOARD");
        dashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashbordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dLayout = new javax.swing.GroupLayout(d);
        d.setLayout(dLayout);
        dLayout.setHorizontalGroup(
            dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashbord, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        dLayout.setVerticalGroup(
            dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashbord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, -1));

        e.setBackground(new java.awt.Color(197, 179, 88));
        e.setForeground(new java.awt.Color(197, 179, 88));
        e.setPreferredSize(new java.awt.Dimension(142, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("MANAGE QUESTIONS");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout eLayout = new javax.swing.GroupLayout(e);
        e.setLayout(eLayout);
        eLayout.setHorizontalGroup(
            eLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        eLayout.setVerticalGroup(
            eLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, -1));

        g.setBackground(new java.awt.Color(197, 179, 88));
        g.setForeground(new java.awt.Color(197, 179, 88));

        user.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setText("USER MANAGEMENT");
        user.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout gLayout = new javax.swing.GroupLayout(g);
        g.setLayout(gLayout);
        gLayout.setHorizontalGroup(
            gLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gLayout.setVerticalGroup(
            gLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 30));

        h.setBackground(new java.awt.Color(197, 179, 88));
        h.setForeground(new java.awt.Color(197, 179, 88));
        h.setPreferredSize(new java.awt.Dimension(142, 30));

        account1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        account1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        account1.setText("SYSTEM LOGS");
        account1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                account1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hLayout = new javax.swing.GroupLayout(h);
        h.setLayout(hLayout);
        hLayout.setHorizontalGroup(
            hLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(account1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        hLayout.setVerticalGroup(
            hLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(account1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 160, -1));

        i.setBackground(new java.awt.Color(44, 62, 80));
        i.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 179, 88)));

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow20.png"))); // NOI18N

        Back.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        Back.setForeground(new java.awt.Color(197, 179, 88));
        Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout iLayout = new javax.swing.GroupLayout(i);
        i.setLayout(iLayout);
        iLayout.setHorizontalGroup(
            iLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iLayout.createSequentialGroup()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        iLayout.setVerticalGroup(
            iLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel2.add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void user1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_user1MouseClicked

    private void nameeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameeeActionPerformed

    private void emaillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emaillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emaillActionPerformed

    private void passsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passsActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
                                                                                                     
    config conf = new config();
    String name = nameee.getText();
    String email = emaill.getText();
    String userType = type.getSelectedItem().toString();
    String imagee = (destination == null || destination.isEmpty()) 
                    ? "src/resources/default_user.png" 
                    : destination;
    
    String defaultPassword = "P@ssw0rd";

    if(name.isEmpty() || email.isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(null, "Please fill in all fields!");
        return;
    }

    String hashedDefault = conf.hashPassword(defaultPassword);
    
    String sqlUser = "INSERT INTO tbl_user (u_name, u_email, u_pass, u_type, u_status, u_image) "
            + "VALUES (?, ?, ?, ?, ?, ?)";
    if(conf.addRecord(sqlUser, name, email, hashedDefault, userType, "Approved", imagee) == 1) {
    //if(conf.insertData(sqlUser)){
        String uid = "";
        
        try {
            String fetchID = "SELECT u_id FROM tbl_user WHERE u_email = '" + email + "'";
            java.sql.ResultSet rs = conf.getData(fetchID);
            if(rs.next()){
                uid = rs.getString("u_id");
            }
            conf.closeResult(rs); 
        } catch (SQLException ex) {
            System.out.println("Fetch ID Error: " + ex.getMessage());
        }

        // 3. Insert into specific profile table
        if (!uid.equals("")) {
            String sqlProfile = "";
            if(userType.equalsIgnoreCase("Teacher")){
                sqlProfile = "INSERT INTO tbl_teacher (t_u_id, t_name, t_status) "
                        + "VALUES ('"+uid+"', '"+name+"', 'Approved')";
            } else if(userType.equalsIgnoreCase("Student")){
                sqlProfile = "INSERT INTO tbl_student (s_u_id, s_name, s_status) "
                        + "VALUES ('"+uid+"', '"+name+"', 'Approved')";
            } else if(userType.equalsIgnoreCase("Admin")){
                sqlProfile = "INSERT INTO tbl_admin (a_u_id, a_name, a_status) "
                        + "VALUES ('"+uid+"', '"+name+"', 'Approved')";
            }

            if(!sqlProfile.equals("")){
                conf.insertData(sqlProfile); 
            }
        }
        
        javax.swing.JOptionPane.showMessageDialog(null, "User created! Default password is: " + defaultPassword);
        
        conf.logEvent("Admin added user: " + email + " with default password.");
        new manageUsers().setVisible(true);
        this.dispose();
    } else {
        javax.swing.JOptionPane.showMessageDialog(null, "Registration Failed.");
    }





    }//GEN-LAST:event_saveMouseClicked

    private void changepicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepicMouseClicked
        JFileChooser fileChooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "jpg", "png", "jpeg");
            fileChooser.setFileFilter(filter);

            int result = fileChooser.showOpenDialog(null);

            if (result == JFileChooser.APPROVE_OPTION) {
                File selectedFile = fileChooser.getSelectedFile();
                destination = selectedFile.getAbsolutePath(); 

                ImageIcon icon = new ImageIcon(destination);
                Image img = icon.getImage().getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
                image.setIcon(new ImageIcon(img));
            }
    }//GEN-LAST:event_changepicMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
                                          
        manageUsers mu = new manageUsers();
        mu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        editUser editFrame = new editUser();
        editFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountMouseClicked

    private void dashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashbordMouseClicked
        adminDashboard dashFrame = new adminDashboard();
        dashFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashbordMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        manageQ manageqFrame = new manageQ();
        manageqFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        manageUsers userstableFrame = new manageUsers();
        userstableFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userMouseClicked

    private void userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_userMouseEntered

    private void account1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_account1MouseClicked
        sysLogs tt = new sysLogs();
        tt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_account1MouseClicked

    private void evaluationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluationsMouseClicked
        manageEvaluations ad = new manageEvaluations();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_evaluationsMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        editUser editFrame = new editUser();
        editFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        adminDashboard ad = new adminDashboard();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JPanel CANCEL;
    private javax.swing.JPanel EMAIL;
    private javax.swing.JPanel ID;
    private javax.swing.JPanel NAME;
    private javax.swing.JPanel PASS;
    private javax.swing.JPanel SAVE;
    private javax.swing.JPanel USERTYPE;
    private javax.swing.JPanel a;
    private javax.swing.JLabel account;
    private javax.swing.JLabel account1;
    private javax.swing.JPanel b;
    private javax.swing.JLabel back;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel cancel;
    private javax.swing.JPanel change;
    private javax.swing.JLabel changepic;
    private javax.swing.JPanel d;
    private javax.swing.JLabel dashbord;
    private javax.swing.JPanel e;
    private java.awt.Label email;
    private java.awt.TextField emaill;
    private javax.swing.JLabel evaluations;
    private javax.swing.JPanel g;
    private javax.swing.JPanel h;
    private javax.swing.JPanel i;
    private java.awt.Label id;
    private javax.swing.JPanel idd;
    private javax.swing.JLabel image;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label name;
    public javax.swing.JLabel namee;
    private java.awt.TextField nameee;
    private java.awt.Label pass;
    private java.awt.TextField passs;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel save;
    private javax.swing.JLabel totp4;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user1;
    private java.awt.Label usertype;
    // End of variables declaration//GEN-END:variables
}
