/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package z_teacher;


import authenticate.logIn;
import config.config;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import x_admin.adminDashboard;
import x_admin.manageQ;
import x_admin.sysLogs;
/**
 *
 * @author juls
 */
public class tDashboard extends javax.swing.JFrame {

    private String currentImagePath;
    private String currentUserName;
    
    public tDashboard(String name, String imagePath) {
        if (config.stopIllegalAccess(this)) return;
        initComponents();
        this.currentUserName = name;
        this.currentImagePath = imagePath;
        namee.setText(currentUserName);
        setupDashboard();
        displayResults(); 
        displayStatistics();

        //OTTTTTTTTTTTTTTTEN
    }

    public tDashboard() {
    if (config.stopIllegalAccess(this)) return;
    initComponents();
    
    // 1. Get data from the global session
    this.currentUserName = config.getName();
    this.currentImagePath = config.getImage();
    
    // 2. SET THE NAME LABEL
    namee.setText(this.currentUserName);
    
    // 3. LOAD THE IMAGE (using the remedy function)
    setupDashboard(); 
    
    config conf = new config();
    conf.logEvent("Teacher Dashboard Accessed");
    
    displayResults(); 
    displayStatistics();
}
    
      private void setupDashboard() {
        
        config conf = new config();
        // Hover effects
        conf.manageHover(a);  conf.manageHover(d);
         conf.manageHover(h);

        conf.manageHover(C); 
        
        // Update the image using the crop logic
        if (currentImagePath != null && !currentImagePath.isEmpty()) {
        // Pass the path, null for byte array, and the label dimensions
        profile.setIcon(conf.resizeImage(currentImagePath, null, profile.getWidth(), profile.getHeight()));
    }
        
    }
      
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        a = new javax.swing.JPanel();
        account = new javax.swing.JLabel();
        d = new javax.swing.JPanel();
        dashbord = new javax.swing.JLabel();
        i = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        h = new javax.swing.JPanel();
        logs = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        user1 = new javax.swing.JLabel();
        profile = new config.CircularLabel();
        namee = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_results = new javax.swing.JTable();
        C = new javax.swing.JPanel();
        lbl_totalAvg = new javax.swing.JLabel();
        users5 = new javax.swing.JLabel();
        C1 = new javax.swing.JPanel();
        lbl_totalStudents = new javax.swing.JLabel();
        users6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 33, 71));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(45, 52, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setBackground(new java.awt.Color(197, 179, 88));
        a.setForeground(new java.awt.Color(197, 179, 88));
        a.setPreferredSize(new java.awt.Dimension(142, 30));

        account.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        account.setText("MY PROFILE");
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout aLayout = new javax.swing.GroupLayout(a);
        a.setLayout(aLayout);
        aLayout.setHorizontalGroup(
            aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(account, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        aLayout.setVerticalGroup(
            aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(account, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, -1));

        d.setBackground(new java.awt.Color(197, 179, 88));
        d.setForeground(new java.awt.Color(197, 179, 88));
        d.setPreferredSize(new java.awt.Dimension(142, 30));
        d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dMouseEntered(evt);
            }
        });
        d.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashbord.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        dashbord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashbord.setText("DASHBOARD");
        dashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashbordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashbordMouseEntered(evt);
            }
        });
        d.add(dashbord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, -1));

        i.setBackground(new java.awt.Color(44, 62, 80));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow20.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        Back.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        Back.setForeground(new java.awt.Color(240, 240, 240));
        Back.setText("Log out");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout iLayout = new javax.swing.GroupLayout(i);
        i.setLayout(iLayout);
        iLayout.setHorizontalGroup(
            iLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iLayout.createSequentialGroup()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        iLayout.setVerticalGroup(
            iLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 90, 30));

        h.setBackground(new java.awt.Color(197, 179, 88));
        h.setForeground(new java.awt.Color(197, 179, 88));
        h.setPreferredSize(new java.awt.Dimension(142, 30));

        logs.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        logs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logs.setText("MY LOGS");
        logs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hLayout = new javax.swing.GroupLayout(h);
        h.setLayout(hLayout);
        hLayout.setHorizontalGroup(
            hLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        hLayout.setVerticalGroup(
            hLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 430));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setForeground(new java.awt.Color(240, 240, 240));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        user1.setForeground(new java.awt.Color(197, 179, 88));
        user1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user1.setText("TEACHER DASHBOARD");
        user1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user1MouseClicked(evt);
            }
        });
        jPanel3.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 480, 70));

        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        jPanel3.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 60));

        namee.setBackground(new java.awt.Color(44, 62, 80));
        namee.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        namee.setForeground(new java.awt.Color(240, 240, 240));
        jPanel3.add(namee, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 140, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        table_results.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_results);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 620, 220));

        C.setBackground(new java.awt.Color(45, 52, 54));
        C.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_totalAvg.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        lbl_totalAvg.setForeground(new java.awt.Color(240, 240, 240));
        lbl_totalAvg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C.add(lbl_totalAvg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 120, 40));

        users5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        users5.setForeground(new java.awt.Color(240, 240, 240));
        users5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        users5.setText("OVERALL RATING");
        C.add(users5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        jPanel1.add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 240, 110));

        C1.setBackground(new java.awt.Color(45, 52, 54));
        C1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_totalStudents.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        lbl_totalStudents.setForeground(new java.awt.Color(240, 240, 240));
        lbl_totalStudents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C1.add(lbl_totalStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 120, 40));

        users6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        users6.setForeground(new java.awt.Color(240, 240, 240));
        users6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        users6.setText("STUDENTS EVALUATED");
        C1.add(users6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        jPanel1.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 240, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void displayResults() {
        String sql = "SELECT DISTINCT e_date AS 'Date', "
                   + "ROUND(e_average, 2) AS 'Rating', "
                   + "e_remarks AS 'Remarks' "
                   + "FROM tbl_evaluation WHERE t_u_id = ?"; 

        try (java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:aes.db");
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {

            // 2. This line now works because there is exactly one '?' in the SQL above
            pstmt.setInt(1, Integer.parseInt(config.getID()));

            try (java.sql.ResultSet rs = pstmt.executeQuery()) {
                table_results.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            }

        } catch (java.sql.SQLException e) {
            System.out.println("Display Error: " + e.getMessage());
        } catch (NumberFormatException e) {
            System.out.println("ID Error: Invalid Teacher ID format");
        }
    }
    
 public void displayStatistics() {
    String sql = "SELECT COUNT(s_u_id), AVG(e_average) FROM tbl_evaluation WHERE t_u_id = ?";
    
    try (Connection conn = DriverManager.getConnection("jdbc:sqlite:aes.db");
         PreparedStatement pst = conn.prepareStatement(sql)) {
        
        pst.setString(1, config.getID());
        
        try (ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                // lbl_totalStudents and lbl_totalAvg are the names in your .form
                lbl_totalStudents.setText(String.valueOf(rs.getInt(1)));
                
                // Formats the average to 2 decimal places (e.g., 85.50)
                double avg = rs.getDouble(2);
                lbl_totalAvg.setText(String.format("%.2f", avg));
            }
        }
    } catch (SQLException e) {
        System.out.println("Error calculating statistics: " + e.getMessage());
    }
}
    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        teditUser accFrame = new teditUser();
        accFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountMouseClicked

    private void dashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashbordMouseClicked
        tDashboard c= new tDashboard();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashbordMouseClicked

    private void dashbordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashbordMouseEntered

    }//GEN-LAST:event_dashbordMouseEntered

    private void dMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseEntered

    }//GEN-LAST:event_dMouseEntered

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        adminDashboard ad = new adminDashboard();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        int confirm = javax.swing.JOptionPane.showConfirmDialog(null,
            "Do you really want to log out?", "Logout", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            config.setSession(null, null, null, null, null);
            logIn loginFrame = new logIn();
            loginFrame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_BackMouseClicked

    private void logsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logsMouseClicked
        tLogs tt = new tLogs();
        tt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logsMouseClicked

    private void user1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_user1MouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        teditUser editFrame = new teditUser();
        editFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JPanel C;
    private javax.swing.JPanel C1;
    private javax.swing.JPanel a;
    private javax.swing.JLabel account;
    private javax.swing.JLabel back;
    private javax.swing.JPanel d;
    private javax.swing.JLabel dashbord;
    private javax.swing.JPanel h;
    private javax.swing.JPanel i;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_totalAvg;
    private javax.swing.JLabel lbl_totalStudents;
    private javax.swing.JLabel logs;
    public javax.swing.JLabel namee;
    private javax.swing.JLabel profile;
    private javax.swing.JTable table_results;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel users5;
    private javax.swing.JLabel users6;
    // End of variables declaration//GEN-END:variables
}
